server:
  port: 8086

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# African's Talking SMS (Sandbox)
africastalking:
  username: ${AT_USERNAME}
  api-key: ${AT_API_KEY}
  sms-url: ${AT_SMS_URL}

# Firebase FCM
firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}
