-- D3: baseline schema for review-service (reviews).

CREATE TABLE IF NOT EXISTS reviews (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id               BIGINT,
    customer_id              BIGINT,
    worker_id                BIGINT,
    rating                   INTEGER NOT NULL,
    comment                  VARCHAR(255),
    customer_name            VARCHAR(255),
    customer_profile_picture VARCHAR(255),
    created_at               TIMESTAMP(6)
);
