-- D3: baseline schema for booking-service (bookings, chat_messages).

CREATE TABLE IF NOT EXISTS bookings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT,
    worker_id      BIGINT,
    worker_name    VARCHAR(255),
    service_type   VARCHAR(255),
    amount         NUMERIC(38,2),
    min_amount     NUMERIC(38,2),
    max_amount     NUMERIC(38,2),
    notes          VARCHAR(255),
    customer_phone VARCHAR(255),
    booking_image  VARCHAR(255),
    booking_images TEXT,
    pricing_style  VARCHAR(255),
    status         VARCHAR(255),
    scheduled_at   TIMESTAMP(6),
    created_at     TIMESTAMP(6),
    quoted_amount  NUMERIC(38,2),
    quote_status   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT,
    conversation_id VARCHAR(255),
    sender_id       VARCHAR(255),
    sender_name     VARCHAR(255),
    text            VARCHAR(255),
    timestamp       BIGINT
);
