-- RETENTION: customers save favorite workers for one-tap rebooking
CREATE TABLE IF NOT EXISTS favorites (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id BIGINT NOT NULL,
    worker_id        BIGINT NOT NULL,
    created_at       TIMESTAMP,
    CONSTRAINT uk_favorites UNIQUE (customer_user_id, worker_id)
);
