-- D3: baseline schema for payment-service (payments).

CREATE TABLE IF NOT EXISTS payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id         BIGINT,
    customer_id        BIGINT,
    worker_id          BIGINT,
    amount             NUMERIC(38,2),
    commission_rate    NUMERIC(38,2),
    commission_amount  NUMERIC(38,2),
    worker_amount      NUMERIC(38,2),
    status             VARCHAR(255),
    paystack_reference VARCHAR(255),
    paystack_status    VARCHAR(255),
    authorization_url  TEXT,
    customer_email     VARCHAR(255),
    customer_phone     VARCHAR(255),
    worker_phone       VARCHAR(255),
    worker_name        VARCHAR(255),
    service_type       VARCHAR(255),
    payout_status      VARCHAR(255),
    payout_reference   VARCHAR(255),
    created_at         TIMESTAMP(6)
);
