-- SUBSCRIPTIONS: worker "Pro" plan purchases via Paystack
CREATE TABLE IF NOT EXISTS subscription_payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_user_id    BIGINT,
    reference         VARCHAR(255) UNIQUE,
    amount            NUMERIC(38, 2),
    status            VARCHAR(255),
    authorization_url VARCHAR(1024),
    created_at        TIMESTAMP
);
