server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fixerhub
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# MTN MoMo Collections API (Sandbox)
fixerhub:
  commission-rate: ${COMMISSION_RATE}

momo:
  base-url: ${MOMO_BASE_URL}
  subscription-key: ${MOMO_SUBSCRIPTION_KEY}
  api-user: ${MOMO_API_USER}
  api-key: ${MOMO_API_KEY}
  environment: ${MOMO_ENVIRONMENT}
  callback-url: ${MOMO_CALLBACK_URL}
  currency: ${MOMO_CURRENCY}
