-- D3: baseline schema for worker-service (workers, worker_portfolio).

CREATE TABLE IF NOT EXISTS workers (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT,
    email                     VARCHAR(255),
    name                      VARCHAR(255),
    phone                     VARCHAR(255),
    skill                     VARCHAR(255),
    location                  VARCHAR(255),
    rating                    DOUBLE PRECISION,
    available                 BOOLEAN,
    latitude                  DOUBLE PRECISION,
    longitude                 DOUBLE PRECISION,
    verified                  BOOLEAN,
    profile_picture           VARCHAR(255),
    verification_document_url VARCHAR(255),
    id_front_url              VARCHAR(255),
    id_back_url               VARCHAR(255),
    headshot_url              VARCHAR(255),
    verification_status       VARCHAR(255),
    verification_note         VARCHAR(255),
    min_price                 NUMERIC(38,2),
    max_price                 NUMERIC(38,2),
    pricing_style             VARCHAR(255),
    momo_network              VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS worker_portfolio (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id  BIGINT,
    image_url  VARCHAR(255),
    caption    VARCHAR(255),
    created_at TIMESTAMP(6)
);
