-- D3: baseline schema for auth-service (users, reports, refresh_tokens).
-- Idempotent: safe on a fresh DB and on an existing Hibernate-created DB
-- (baseline-on-migrate skips this file when tables already exist).

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    name            VARCHAR(255),
    phone           VARCHAR(255),
    profile_picture VARCHAR(255),
    reset_otp       VARCHAR(255),
    otp_expires_at  TIMESTAMP(6),
    role            VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS reports (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id              BIGINT,
    reporter_email           VARCHAR(255),
    reporter_name            VARCHAR(255),
    reporter_profile_picture VARCHAR(255),
    category                 VARCHAR(255),
    description              TEXT,
    status                   VARCHAR(255),
    created_at               TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(128) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked    BOOLEAN NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_refresh_token ON refresh_tokens (token);
